"""udev rules generation for persistent device naming."""

from pathlib import Path

from .config import REGISTRY_DIR
from .registry import Device
from .ssh import SSHConnection


UDEV_RULES_FILE = REGISTRY_DIR / "udev" / "99-esp-devices.rules"


def generate_rules(devices: list[Device]) -> str:
    """Generate udev rules for devices."""
    lines = [
        "# ESP device naming rules",
        "# Generated by esp-remote",
        "# Install to /etc/udev/rules.d/99-esp-devices.rules",
        "",
    ]

    for device in devices:
        if not device.usb_path:
            continue

        # Create rule based on USB path (KERNELS)
        # Example: SUBSYSTEM=="tty", KERNELS=="1-1.2", SYMLINK+="esp-motor-left"
        lines.append(
            f'SUBSYSTEM=="tty", KERNELS=="{device.usb_path}", '
            f'SYMLINK+="{device.name}", MODE="0666"'
        )

    return "\n".join(lines) + "\n"


def save_rules(devices: list[Device]):
    """Save udev rules to registry."""
    UDEV_RULES_FILE.parent.mkdir(parents=True, exist_ok=True)
    rules = generate_rules(devices)
    UDEV_RULES_FILE.write_text(rules)
    return rules


def install_rules(ssh: SSHConnection, rules: str) -> tuple[bool, str]:
    """Install udev rules on remote host."""
    # Write rules file
    safe_rules = rules.replace("'", "'\"'\"'")
    out, err, code = ssh.run(
        f"echo '{safe_rules}' | sudo tee /etc/udev/rules.d/99-esp-devices.rules > /dev/null"
    )
    if code != 0:
        return False, f"Failed to write rules: {err}"

    # Reload udev
    out, err, code = ssh.run("sudo udevadm control --reload-rules && sudo udevadm trigger")
    if code != 0:
        return False, f"Failed to reload udev: {err}"

    return True, "udev rules installed"


def get_usb_path(ssh: SSHConnection, device: str) -> str:
    """Get USB path (KERNELS) for a device.

    Returns the USB port path like '3-2' which is stable across reboots.
    """
    # Get KERNELS that looks like a USB path (e.g., "3-2" not "3-2:1.0")
    out, err, code = ssh.run(
        f"udevadm info -a -n {device} 2>/dev/null | grep KERNELS | "
        f"grep -E '\"[0-9]+-[0-9]+\"' | head -1 | cut -d'\"' -f2"
    )
    return out.strip() if code == 0 else ""
